In [1]:
import numpy as np

def discrete_fourier_transform(sequence):
    """
    Perform Discrete Fourier Transform on a given sequence.
    
    Args:
    sequence (list of int/float): The input sequence for DFT.

    Returns:
    list: The DFT coefficients.
    """
    N = len(sequence)
    sequence = np.array(sequence)
    n = np.arange(N)
    k = n.reshape((N, 1))
    M = np.cos(-2j * np.pi * k * n / N)
    return np.dot(M, sequence)

# Test the function with the provided sequence
sequence = [-2, 1, 0, -1, 0, 1]
dft_result = discrete_fourier_transform(sequence)

In [2]:
dft_result

array([-1.00000000e+00+0.00000000e+00j, -6.66133815e-16+5.55111512e-16j,
       -4.00000000e+00-1.11022302e-15j, -3.00000000e+00-2.14375088e-15j,
       -4.00000000e+00-2.22044605e-15j,  1.22124533e-15+3.99680289e-15j])

In [3]:
dft_real_approx = np.real_if_close(dft_result, tol=1000)
dft_real_approx

array([-1.00000000e+00, -6.66133815e-16, -4.00000000e+00, -3.00000000e+00,
       -4.00000000e+00,  1.22124533e-15])

In [6]:
import numpy as np

def discrete_fourier_transform_trig(sequence):
    """
    Perform Discrete Fourier Transform using trigonometric expressions.

    Args:
    sequence (list of int/float): The input sequence for DFT.

    Returns:
    list: The DFT coefficients.
    """
    N = len(sequence)
    sequence = np.array(sequence)
    n = np.arange(N)
    k = n.reshape((N, 1))
    # Using trigonometric expressions for the DFT matrix
    M = np.cos(-2 * np.pi * k * n / N)
    return np.dot(M, sequence)

# Test the function with the provided sequence
sequence = [-2, 1, 0, -1, 0, 1]
dft_result_trig = discrete_fourier_transform_trig(sequence)

In [7]:
dft_result_trig

array([-1.00000000e+00,  0.00000000e+00, -4.00000000e+00, -3.00000000e+00,
       -4.00000000e+00, -1.16573418e-15])